In [3]:
import torch

In [7]:
x = torch.tensor([1,2,3])

In [8]:
x

tensor([1, 2, 3])

In [9]:
x[2]

tensor(3)

In [10]:
x.shape

torch.Size([3])

In [11]:
x + torch.tensor([4,4,4])

tensor([5, 6, 7])

In [12]:
x + 5

tensor([6, 7, 8])

In [13]:
x = torch.Tensor([[1,2,3], [4,5,6]])

In [14]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
x = torch.randn((1,5))

In [20]:
x

tensor([[ 0.6847, -0.4783,  0.5355,  0.9366,  0.8377]])

In [12]:
x = torch.randn((2,3))

In [13]:
x

tensor([[ 0.5415, -1.0387, -1.0374],
        [ 0.7313,  0.6595,  0.2073]])