In [5]:
import torch

In [6]:
input_img = torch.randn([1,10])

In [7]:
input_img

tensor([[ 0.5803,  0.7803, -0.0305, -0.7599,  0.2355,  0.5078, -0.5101,  2.0663,
          0.7625, -1.3193]])

In [8]:
weights = torch.randn_like(input_img)

In [9]:
weights

tensor([[-0.1836,  0.5832,  0.6117,  0.4274, -1.0078, -0.6821, -0.7279,  0.7862,
          2.1351,  1.2384]])

In [10]:
bias = torch.randn([1,1])

In [11]:
bias

tensor([[2.1210]])

In [12]:
torch.sum(input_img * weights)

tensor(1.4114)

In [13]:
output = torch.sum(input_img * weights) + bias

In [14]:
output

tensor([[3.5325]])

In [15]:
# activation function: sigmoid 01
def sigmoid(x):
    return 1/(1+torch.exp(-x))

In [16]:
output = sigmoid(output)

In [17]:
output

tensor([[0.9716]])