In [1]:
import torch

In [2]:
x = torch.randn((1,5), requires_grad=True)

In [3]:
x

tensor([[-0.3796,  1.6146,  1.0180, -2.1651, -0.7008]], requires_grad=True)

In [4]:
b = x + 2

In [5]:
# notice the grad_fn / Add function with backward prop
# computational graph was computed
b

tensor([[ 1.6204,  3.6146,  3.0180, -0.1651,  1.2992]], grad_fn=<AddBackward0>)

In [6]:
c = b * 2

In [7]:
# added the mul function
c

tensor([[ 3.2409,  7.2292,  6.0359, -0.3302,  2.5984]], grad_fn=<MulBackward0>)

In [8]:
c = c.mean()

In [9]:
# added the mean
c

tensor(3.7548, grad_fn=<MeanBackward0>)

In [10]:
# there is nothing before the backward propagation
x.grad

In [11]:
# to do a backward prop
c.backward()

In [12]:
# now there is a grad
x.grad

tensor([[0.4000, 0.4000, 0.4000, 0.4000, 0.4000]])