In [2]:
import torch

In [3]:
input_img = torch.randn([1,10])

In [4]:
input_img

tensor([[ 1.0378, -2.5470,  0.0192,  0.5376, -0.7009,  1.7684, -0.6898,  1.0698,
         -1.1768,  1.5831]])

In [5]:
weights = torch.randn_like(input_img)

In [6]:
weights

tensor([[-0.2997, -2.6875, -0.3815,  0.9115, -0.4368,  0.4132, -1.4378, -1.0191,
         -2.6499,  0.7148]])

In [7]:
bias = torch.randn([1,1])

In [8]:
bias

tensor([[-0.7055]])

In [9]:
output = torch.mm(input_img, weights.view(10, 1)) + bias

In [10]:
output

tensor([[11.4999]])

In [11]:
# activation function: sigmoid 01
def sigmoid(x):
    return 1/(1+torch.exp(-x))

In [12]:
output = sigmoid(output)

In [13]:
output

tensor([[1.0000]])