In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3])

In [3]:
x

tensor([1, 2, 3])

In [4]:
x[2]

tensor(3)

In [5]:
x.shape

torch.Size([3])

In [6]:
x + torch.tensor([4,4,4])

tensor([5, 6, 7])

In [7]:
x + 5

tensor([6, 7, 8])

In [8]:
x = torch.Tensor([[1,2,3], [4,5,6]])

In [9]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
x = torch.randn((1,5))

In [11]:
x

tensor([[ 0.2327,  0.0919,  0.5782,  1.0405, -0.1662]])

In [12]:
x = torch.randn((2,3))

In [13]:
x

tensor([[ 0.5415, -1.0387, -1.0374],
        [ 0.7313,  0.6595,  0.2073]])